#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
cced2_utils.py

Minimal implementation of CCED2 (Cross-Class Embedding Distance 2).

This script provides two commands:

- fit:
    Learns kNN reference, Mahalanobis reference (Ledoit–Wolf shrinkage),
    and z-score normalisation parameters from an In-distribution (InD)
    embedding set and saves them to a directory.

- score:
    Loads the trained references and z-score parameters, computes kNN_z,
    Mahalanobis_z, and CCED2 scores for any target embedding set, and saves
    the results as .npy file(s).

Notes for reproducibility:
- Embedding directories are assumed to contain multiple `embeddings_*.npy`
  files (shape [N_i, D]) as generated by scripts like `dump_known56_features.py`.
- By default, we use filenames consistent with the paper repository:
    knn_dapt.pkl, maha_dapt.pkl, cced2_norm.json
  (override via CLI if needed).

Example usage:

1) Fit CCED2 models on InD embeddings:

    python cced2_utils.py fit \\
      --embeddings_dir /path/to/ind_embeddings \\
      --out_dir        ./weights/cced2 \\
      --k              50

2) Score CCED2 on a target dataset using the trained models:

    python cced2_utils.py score \\
      --model_dir      ./weights/cced2 \\
      --embeddings_dir /path/to/target_embeddings \\
      --out_path       ./results/score_cced2.npy \\
      --save_components

This will save:
  - ./results/score_cced2.npy          (CCED2 = kNN_z + Mahalanobis_z)
  - ./results/score_cced2_knn_z.npy
  - ./results/score_cced2_maha_z.npy
(and optionally raw distances if --save_raw is set).
"""

import os
import sys
import json
import glob
import argparse
from pathlib import Path
from typing import Tuple, Optional

import numpy as np
from sklearn.neighbors import NearestNeighbors
from sklearn.covariance import LedoitWolf
import joblib


# -----------------------------
# I/O helpers
# -----------------------------
def load_embeddings_from_dir(
    emb_dir: str,
    pattern: str = "embeddings_*.npy",
    dtype=np.float32
) -> np.ndarray:
    """
    Loads all embedding files matching `pattern` from `emb_dir`
    and concatenates them into a single [N, D] array.
    """
    emb_files = sorted(glob.glob(os.path.join(emb_dir, pattern)))
    if not emb_files:
        raise FileNotFoundError(f"No embeddings matched: {emb_dir}/{pattern}")

    arrs = []
    for p in emb_files:
        e = np.load(p)
        if e.ndim != 2:
            raise ValueError(f"Expected 2D array in {p}, got shape {e.shape}")
        arrs.append(e.astype(dtype, copy=False))

    return np.concatenate(arrs, axis=0)


def _safe_std(x: np.ndarray, eps: float = 1e-8) -> float:
    return float(x.std() + eps)


# -----------------------------
# FIT
# -----------------------------
def fit_cced2(
    emb_dir: str,
    out_dir: str,
    k: int = 50,
    knn_fname: str = "knn_dapt.pkl",
    maha_fname: str = "maha_dapt.pkl",
    norm_fname: str = "cced2_norm.json",
) -> None:
    """
    Learns CCED2 references (kNN & Mahalanobis) and z-score parameters from
    InD embeddings, then saves them to out_dir.
    """
    out_path = Path(out_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    print(f"[fit] loading InD embeddings from: {emb_dir}")
    E = load_embeddings_from_dir(emb_dir)  # [N, D]
    N, D = E.shape
    print(f"[fit] embeddings shape: {E.shape}")

    # Train kNN reference
    k_eff = min(int(k), max(1, int(N)))
    print(f"[fit] training kNN (k={k_eff}) ...")
    knn = NearestNeighbors(n_neighbors=k_eff, algorithm="auto")
    knn.fit(E)

    # Fit Mahalanobis mean & covariance using Ledoit-Wolf shrinkage
    print("[fit] fitting LedoitWolf covariance ...")
    lw = LedoitWolf()
    lw.fit(E.astype(np.float64))
    mu = lw.location_.astype(np.float32, copy=False).reshape(1, -1)   # [1, D]
    precision = lw.precision_.astype(np.float32, copy=False)          # [D, D]

    # Compute distances on InD to estimate z-score parameters
    print("[fit] computing kNN & Mahalanobis distances on InD ...")
    dists, _ = knn.kneighbors(E, n_neighbors=k_eff)
    d_knn = dists.mean(axis=1).astype(np.float64)  # [N]

    diff = (E.astype(np.float32) - mu)             # [N, D]
    maha_raw = diff @ precision                    # [N, D]
    d_maha = np.sqrt(np.einsum("nd,nd->n", diff, maha_raw).astype(np.float64) + 1e-12)

    mk = float(d_knn.mean())
    sk = _safe_std(d_knn)
    mm = float(d_maha.mean())
    sm = _safe_std(d_maha)

    print("[fit] z-score stats (InD):")
    print(f"  kNN:  mean={mk:.6f}, std={sk:.6f}")
    print(f"  Maha: mean={mm:.6f}, std={sm:.6f}")

    # Save models and normalization parameters
    print(f"[fit] saving to: {out_path}")
    joblib.dump({"knn": knn, "k": k_eff}, out_path / knn_fname)
    joblib.dump({"mu": mu, "precision": precision}, out_path / maha_fname)

    cfg = {"mk": mk, "sk": sk, "mm": mm, "sm": sm}
    with open(out_path / norm_fname, "w") as f:
        json.dump(cfg, f, indent=2)

    print("[fit] done.")


def _load_cced2_models(
    model_dir: str,
    knn_fname: str = "knn_dapt.pkl",
    maha_fname: str = "maha_dapt.pkl",
    norm_fname: str = "cced2_norm.json",
):
    model_path = Path(model_dir)
    knn = joblib.load(model_path / knn_fname)
    maha = joblib.load(model_path / maha_fname)
    with open(model_path / norm_fname, "r") as f:
        cfg = json.load(f)
    return knn, maha, cfg


# -----------------------------
# SCORE
# -----------------------------
def score_cced2(
    model_dir: str,
    emb_dir: str,
    out_path: str,
    pattern: str = "embeddings_*.npy",
    save_components: bool = False,
    save_raw: bool = False,
    knn_fname: str = "knn_dapt.pkl",
    maha_fname: str = "maha_dapt.pkl",
    norm_fname: str = "cced2_norm.json",
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Computes d_knn^z, d_maha^z, and CCED2 scores for embeddings in `emb_dir`
    using the trained models.

    Always saves CCED2 scores to `out_path`.
    If `save_components` is True, also saves kNN_z and Mahalanobis_z next to out_path.
    If `save_raw` is True, also saves raw distances (kNN_raw, Maha_raw) next to out_path.

    Returns:
        d_knn_z, d_maha_z, cced2_score (all shape [N])
    """
    knn, maha, cfg = _load_cced2_models(model_dir, knn_fname=knn_fname, maha_fname=maha_fname, norm_fname=norm_fname)

    print(f"[score] loading embeddings from: {emb_dir}")
    E = load_embeddings_from_dir(emb_dir, pattern=pattern)  # [N, D]
    print(f"[score] embeddings shape: {E.shape}")

    # kNN distance
    k_eff = int(knn["k"])
    dists, _ = knn["knn"].kneighbors(E, n_neighbors=k_eff)
    d_knn_raw = dists.mean(axis=1).astype(np.float64)

    # Mahalanobis distance
    mu = maha["mu"].astype(np.float32, copy=False)            # [1, D]
    precision = maha["precision"].astype(np.float32, copy=False)
    diff = (E.astype(np.float32) - mu)                        # [N, D]
    maha_lin = diff @ precision                               # [N, D]
    d_maha_raw = np.sqrt(np.einsum("nd,nd->n", diff, maha_lin).astype(np.float64) + 1e-12)

    # z-score normalisation
    mk, sk = float(cfg.get("mk", 0.0)), float(cfg.get("sk", 1.0))
    mm, sm = float(cfg.get("mm", 0.0)), float(cfg.get("sm", 1.0))
    sk = sk if sk > 0 else 1e-8
    sm = sm if sm > 0 else 1e-8

    d_knn_z = ((d_knn_raw - mk) / sk).astype(np.float32)
    d_maha_z = ((d_maha_raw - mm) / sm).astype(np.float32)
    cced2_score = (d_knn_z + d_maha_z).astype(np.float32)

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    np.save(out_path, cced2_score)
    print(f"[score] saved CCED2 scores to: {out_path}")

    if save_components:
        np.save(out_path.with_name(out_path.stem + "_knn_z.npy"), d_knn_z)
        np.save(out_path.with_name(out_path.stem + "_maha_z.npy"), d_maha_z)
        print(f"[score] saved components next to: {out_path}")

    if save_raw:
        np.save(out_path.with_name(out_path.stem + "_knn_raw.npy"), d_knn_raw.astype(np.float32))
        np.save(out_path.with_name(out_path.stem + "_maha_raw.npy"), d_maha_raw.astype(np.float32))
        print(f"[score] saved raw distances next to: {out_path}")

    return d_knn_z, d_maha_z, cced2_score


# -----------------------------
# CLI
# -----------------------------
def main():
    ap = argparse.ArgumentParser()
    subparsers = ap.add_subparsers(dest="command", required=True)

    # fit
    ap_fit = subparsers.add_parser("fit", help="fit CCED2 models on InD embeddings")
    ap_fit.add_argument("--embeddings_dir", required=True,
                        help="directory containing embeddings_*.npy for InD")
    ap_fit.add_argument("--out_dir", required=True,
                        help="directory to save CCED2 models and stats")
    ap_fit.add_argument("--k", type=int, default=50,
                        help="number of neighbours for kNN (default: 50)")
    ap_fit.add_argument("--knn_fname", default="knn_dapt.pkl")
    ap_fit.add_argument("--maha_fname", default="maha_dapt.pkl")
    ap_fit.add_argument("--norm_fname", default="cced2_norm.json")

    # score
    ap_score = subparsers.add_parser("score", help="score CCED2 for a target embeddings directory")
    ap_score.add_argument("--model_dir", required=True,
                          help="directory containing kNN/Maha models and cced2_norm.json")
    ap_score.add_argument("--embeddings_dir", required=True,
                          help="directory containing embeddings_*.npy to be scored")
    ap_score.add_argument("--out_path", required=True,
                          help="output .npy file path for CCED2 scores")
    ap_score.add_argument("--pattern", default="embeddings_*.npy",
                          help="glob pattern for embeddings files (default: embeddings_*.npy)")
    ap_score.add_argument("--save_components", action="store_true",
                          help="also save *_knn_z.npy and *_maha_z.npy next to out_path")
    ap_score.add_argument("--save_raw", action="store_true",
                          help="also save *_knn_raw.npy and *_maha_raw.npy next to out_path")
    ap_score.add_argument("--knn_fname", default="knn_dapt.pkl")
    ap_score.add_argument("--maha_fname", default="maha_dapt.pkl")
    ap_score.add_argument("--norm_fname", default="cced2_norm.json")

    args = ap.parse_args()

    if args.command == "fit":
        fit_cced2(
            emb_dir=args.embeddings_dir,
            out_dir=args.out_dir,
            k=args.k,
            knn_fname=args.knn_fname,
            maha_fname=args.maha_fname,
            norm_fname=args.norm_fname,
        )
    elif args.command == "score":
        score_cced2(
            model_dir=args.model_dir,
            emb_dir=args.embeddings_dir,
            out_path=args.out_path,
            pattern=args.pattern,
            save_components=args.save_components,
            save_raw=args.save_raw,
            knn_fname=args.knn_fname,
            maha_fname=args.maha_fname,
            norm_fname=args.norm_fname,
        )
    else:
        ap.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()