#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
cced2_utils.py

Minimal implementation of CCED2 (Cross-Class Embedding Distance 2).

- fit:
    Learns kNN reference, Mahalanobis reference, and z-score normalisation parameters
    from an In-distribution (InD) embedding set and saves them to a directory.

- score:
    Loads the trained references and z-score parameters, computes CCED2 scores
    for any target embedding set, and saves the results as a .npy file.

Example Usage:

1) Fit CCED2 models on InD embeddings:

    python cced2_utils.py fit \\
      --embeddings_dir /path/to/ind_embeddings \\
      --out_dir        /path/to/cced2_model \\
      --k              50

2) Score CCED2 on a target dataset using the trained models:

    python cced2_utils.py score \\
      --model_dir      /path/to/cced2_model \\
      --embeddings_dir /path/to/target_embeddings \\
      --out_path       /path/to/target_embeddings/score_cced2.npy

The embedding directories are assumed to contain multiple `embeddings_*.npy` files
(shape [N_i, D]), as generated by scripts like `dump_known56_features.py`.
"""

import os
import sys
import json
import glob
import argparse
from pathlib import Path
from typing import Tuple

import numpy as np
from sklearn.neighbors import NearestNeighbors
from sklearn.covariance import LedoitWolf
import joblib


def load_embeddings_from_dir(emb_dir: str,
                             pattern: str = "embeddings_*.npy",
                             dtype=np.float32) -> np.ndarray:
    """
    Loads all `embeddings_*.npy` files matching the pattern from the directory
    and concatenates them into a single [N, D] array.
    """
    emb_files = sorted(glob.glob(os.path.join(emb_dir, pattern)))
    if not emb_files:
        raise FileNotFoundError(f"No embeddings matched: {emb_dir}/{pattern}")
    
    arrs = []
    for p in emb_files:
        e = np.load(p)
        if e.ndim != 2:
            raise ValueError(f"Expected 2D array in {p}, got shape {e.shape}")
        arrs.append(e.astype(dtype, copy=False))
    
    emb = np.concatenate(arrs, axis=0)
    return emb


def fit_cced2(emb_dir: str,
              out_dir: str,
              k: int = 50,
              knn_fname: str = "knn_cced2.pkl",
              maha_fname: str = "maha_cced2.pkl",
              norm_fname: str = "cced2_norm.json") -> None:
    """
    Learns CCED2 references (kNN & Mahalanobis) and z-score parameters from
    InD embeddings, then saves them to out_dir.
    """
    out_path = Path(out_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    # Load InD embeddings
    print(f"[fit_cced2] loading embeddings from: {emb_dir}")
    E = load_embeddings_from_dir(emb_dir)  # [N, D]
    N, D = E.shape
    print(f"[fit_cced2] embeddings shape: {E.shape}")

    # Train kNN reference
    k_eff = min(k, max(1, N))
    print(f"[fit_cced2] training kNN (k={k_eff}) ...")
    knn = NearestNeighbors(n_neighbors=k_eff, algorithm="auto")
    knn.fit(E)

    # Fit Mahalanobis mean & covariance (using Ledoit-Wolf shrinkage)
    print(f"[fit_cced2] fitting LedoitWolf covariance ...")
    # LedoitWolf expects float64 for stability
    lw = LedoitWolf()
    lw.fit(E.astype(np.float64))
    mu = E.mean(axis=0, keepdims=True)  # [1, D]
    precision = lw.precision_           # [D, D]

    # Compute distances on InD to estimate z-score parameters
    print(f"[fit_cced2] computing kNN & Mahalanobis distances on InD ...")
    dists, _ = knn.kneighbors(E, n_neighbors=k_eff)
    d_knn = dists.mean(axis=1)                     # [N]
    
    diff = (E - mu.astype(E.dtype))               # [N, D]
    # Mahalanobis: sqrt( (x-μ)^T Σ^{-1} (x-μ) )
    maha_raw = diff @ precision.astype(E.dtype)   # [N, D]
    d_maha = np.sqrt(np.einsum("nd,nd->n", diff, maha_raw) + 1e-12)  # [N]

    mk = float(d_knn.mean())
    sk = float(d_knn.std() + 1e-8)
    mm = float(d_maha.mean())
    sm = float(d_maha.std() + 1e-8)

    print(f"[fit_cced2] z-normalisation stats:")
    print(f"  kNN:   mean={mk:.6f}, std={sk:.6f}")
    print(f"  Maha:  mean={mm:.6f}, std={sm:.6f}")

    # Save models and normalization parameters
    print(f"[fit_cced2] saving models to: {out_dir}")
    joblib.dump({"knn": knn, "k": k_eff}, out_path / knn_fname)
    joblib.dump({"mu": mu, "precision": precision}, out_path / maha_fname)
    
    cfg = {"mk": mk, "sk": sk, "mm": mm, "sm": sm}
    with open(out_path / norm_fname, "w") as f:
        json.dump(cfg, f, indent=2)

    print("[fit_cced2] done.")


def _load_cced2_models(model_dir: str,
                       knn_fname: str = "knn_cced2.pkl",
                       maha_fname: str = "maha_cced2.pkl",
                       norm_fname: str = "cced2_norm.json"):
    """
    Loads saved kNN / Mahalanobis models and z-score parameters.
    """
    model_path = Path(model_dir)
    knn = joblib.load(model_path / knn_fname)
    maha = joblib.load(model_path / maha_fname)
    with open(model_path / norm_fname, "r") as f:
        cfg = json.load(f)
    return knn, maha, cfg


def score_cced2(model_dir: str,
                emb_dir: str,
                out_path: str,
                pattern: str = "embeddings_*.npy") -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Computes d_knn^z, d_maha^z, and CCED2 scores for embeddings in `emb_dir`
    using the trained models, and saves the CCED2 scores to `out_path`.

    Returns:
        d_knn_z, d_maha_z, cced2_score (all shape [N])
    """
    knn, maha, cfg = _load_cced2_models(model_dir)
    print(f"[score_cced2] loading embeddings from: {emb_dir}")
    E = load_embeddings_from_dir(emb_dir, pattern=pattern)  # [N, D]
    print(f"[score_cced2] embeddings shape: {E.shape}")

    # kNN distance
    k_eff = knn["k"]
    dists, _ = knn["knn"].kneighbors(E, n_neighbors=k_eff)
    d_knn = dists.mean(axis=1)  # [N]

    # Mahalanobis distance
    mu = maha["mu"].astype(E.dtype)           # [1, D]
    precision = maha["precision"].astype(E.dtype)  # [D, D]
    diff = (E - mu)
    maha_raw = diff @ precision               # [N, D]
    d_maha = np.sqrt(np.einsum("nd,nd->n", diff, maha_raw) + 1e-12)

    # z-score normalization
    mk, sk = cfg.get("mk", 0.0), cfg.get("sk", 1.0)
    mm, sm = cfg.get("mm", 0.0), cfg.get("sm", 1.0)
    sk = sk if sk > 0 else 1e-8
    sm = sm if sm > 0 else 1e-8

    d_knn_z = (d_knn - mk) / sk
    d_maha_z = (d_maha - mm) / sm
    cced2_score = d_knn_z + d_maha_z

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    np.save(out_path, cced2_score.astype(np.float32))
    print(f"[score_cced2] saved CCED2 scores to: {out_path}")

    return d_knn_z, d_maha_z, cced2_score


def main():
    ap = argparse.ArgumentParser()
    subparsers = ap.add_subparsers(dest="command", required=True)

    # 'fit' command
    ap_fit = subparsers.add_parser("fit", help="fit CCED2 models on InD embeddings")
    ap_fit.add_argument("--embeddings_dir", required=True,
                        help="directory containing embeddings_*.npy for InD")
    ap_fit.add_argument("--out_dir", required=True,
                        help="directory to save CCED2 models and stats")
    ap_fit.add_argument("--k", type=int, default=50,
                        help="number of neighbours for kNN (default: 50)")

    # 'score' command
    ap_score = subparsers.add_parser("score", help="score CCED2 for a target embeddings directory")
    ap_score.add_argument("--model_dir", required=True,
                          help="directory containing knn_cced2.pkl, maha_cced2.pkl and cced2_norm.json")
    ap_score.add_argument("--embeddings_dir", required=True,
                          help="directory containing embeddings_*.npy to be scored")
    ap_score.add_argument("--out_path", required=True,
                          help="output .npy file path for CCED2 scores")
    ap_score.add_argument("--pattern", default="embeddings_*.npy",
                          help="glob pattern for embeddings files (default: embeddings_*.npy)")

    args = ap.parse_args()

    if args.command == "fit":
        fit_cced2(args.embeddings_dir, args.out_dir, k=args.k)
    elif args.command == "score":
        score_cced2(args.model_dir, args.embeddings_dir, args.out_path, pattern=args.pattern)
    else:
        # This branch might be unreachable due to required=True in subparsers, but good for safety
        ap.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()