"""Validate FRDR table arithmetic/selectors and derive manuscript plot/values.

Input CSVs must be generated by the unchanged original grids after the
all-manifest-file evaluation correction. This script does not fit a model.
"""
import hashlib
import json
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

ROOT=Path(__file__).resolve().parent/'frdr_correction_2026-09-13'


def main():
    receipt=json.loads((ROOT/'execution_receipt.json').read_text())
    assert receipt['manifest_files']==50 and receipt['annotation_files']==44
    assert receipt['annotations']==1157 and receipt['manifest_rows']==44900
    hours=receipt['nominal_hours']
    assert np.isclose(hours,50*1804/3600,rtol=0,atol=1e-12)
    for rel, expected in receipt['generated_sha256'].items():
        assert hashlib.sha256((ROOT/rel).read_bytes()).hexdigest()==expected,rel
    t2=pd.read_csv(ROOT/'results/table2/frdr_quiet_promoter_union_supervised.csv')
    fusion=pd.read_csv(ROOT/'results/fusion/fusion.csv')
    t3=pd.read_csv(ROOT/'results/table3/frdr_table3.csv')
    label=pd.read_csv(ROOT/'results/labels/label_efficiency_agg.csv')
    # Re-derive the reported discrete points from the saved full sweeps.
    for name, idx in [('quiet',0),('promoter',1)]:
        sweep=pd.read_csv(ROOT/f'results/table2/{name}_sweep.csv')
        # The exact original pandas tie selector ran in the recorded remote
        # environment; a local NumPy version need not order equal ties alike.
        nearest=sweep[np.isclose((sweep.FP_h-10).abs(),(sweep.FP_h-10).abs().min(),rtol=0,atol=1e-12)]
        assert any(all(np.isclose(pick[k],t2.iloc[idx][k],rtol=0,atol=1e-12) for k in ['Recall','FP_h','TP','FP']) for _,pick in nearest.iterrows())
    union=pd.read_csv(ROOT/'results/table2/union_sweep.csv')
    feasible=union[union.FP_h<=10.5]
    pick=feasible.iloc[feasible.Recall.argmax()]
    assert all(np.isclose(pick[k],t2.iloc[2][k],rtol=0,atol=1e-12) for k in ['Recall','FP_h','TP','FP'])
    best=fusion.iloc[fusion.Recall.argmax()]
    for df in [t2,fusion,t3]:
        assert np.allclose(df.Recall,df.TP/1157,rtol=0,atol=1e-14)
        assert np.allclose(df.FP_h,df.FP/hours,rtol=0,atol=1e-13)
        assert np.isfinite(df[['Recall','FP_h','TP','FP']].to_numpy()).all()
    points={name:{k:float(t2.iloc[i][k]) for k in ['Recall','FP_h','TP','FP']} for i,name in enumerate(['Quiet','Promoter','Union'])}
    points['Fusion']={k:float(best[k]) for k in ['Recall','FP_h','TP','FP']}
    label300=label[label.N.astype(str)=='300'].iloc[0]
    full=label[label.N.astype(str)=='all'].iloc[0]
    assert np.isclose(full.recall_mean,points['Promoter']['Recall'],rtol=0,atol=1e-14)
    values={'table2':points,'table3':{},'labels300':{'recall_mean':float(label300.recall_mean),'recall_std':float(label300.recall_std),'fp_h_mean':float(label300.fp_h_mean)},'fusion_alpha':float(best.alpha),'nominal_hours':hours}
    assert len(t3)==6
    for encoder, block in t3.groupby('encoder',sort=False):
        key='Perch' if 'perch' in encoder.lower() else 'BEATs+DAPT'
        assert key not in values['table3']
        values['table3'][key]={row['score'].replace('CCED2_z','CCED2'):{k:float(row[k]) for k in ['Recall','FP_h','TP','FP']} for _,row in block.iterrows()}
    assert set(values['table3'])=={'BEATs+DAPT','Perch'}
    output=ROOT/'manuscript'; output.mkdir(exist_ok=True)
    fig,ax=plt.subplots(figsize=(8.2,5.4))
    formats={'Quiet':('o','#4C78A8',(-10,21),'right'),
             'Promoter':('D','#F58518',(12,-27),'left'),
             'Union':('^','#54A24B',(-12,14),'right'),
             'Fusion':('s','#B279A2',(12,21),'left')}
    for name,v in points.items():
        marker,colour,offset,alignment=formats[name]
        ax.scatter(v['FP_h'],v['Recall'],s=120,marker=marker,color=colour,edgecolor='black',linewidth=.8,zorder=3,label=name)
        ax.annotate(f"{name}\nrecall {v['Recall']:.3f}",(v['FP_h'],v['Recall']),xytext=offset,textcoords='offset points',ha=alignment,fontsize=9)
    ax.axvline(10,color='0.5',linestyle='--',linewidth=1,label='Target FP/h = 10')
    x=[v['FP_h'] for v in points.values()]
    ax.set_xlim(min(x)-.15,max(x)+.25)
    ax.set_ylim(0,.55)
    ax.set_xlabel('False positives per hour (FP/h)')
    ax.set_ylabel('Recall')
    ax.grid(alpha=.25)
    ax.set_title('FRDR right-whale upcalls: FP/h-constrained operating points')
    ax.legend(loc='center right',frameon=True)
    fig.tight_layout()
    png=output/'Fig3_FRDR_all50.png'
    fig.savefig(png,dpi=300,bbox_inches='tight')
    fig.savefig(output/'Fig3_FRDR_all50.pdf',bbox_inches='tight')
    plt.close(fig)
    values['figure3']=str(png)
    (output/'values.json').write_text(json.dumps(values,indent=2)+'\n')
    print(json.dumps(values,indent=2))


if __name__=='__main__':
    main()

